### ISSUE TITLE
CH Flame and DHW Flame are ON in the dame time

### ISSUE THREAD

**Issue by ovimano** [chomupashchuk/ariston-remotethermo-home-assistant-v2#14]
Hello!

I've observed that Both flames are ON in the same time and it's not possible at Ariston Alteas One Net.

I use the latest version of this component and the latest version of home assistant.

Can you check the code?

Thank you!

![image](https://user-images.githubusercontent.com/8056590/104827128-46eee500-5863-11eb-9292-703f8c82faf5.jpeg)

![image](https://user-images.githubusercontent.com/8056590/104827129-4ce4c600-5863-11eb-9090-08ebe29c2e35.jpeg)

**Comment by chomupashchuk** [comment]
yes, I know, I have the same situation.
The problem is that in requests there are 3 data:
- any flame
- ch flame
- dhw flame
Unfortunately dhw flame is never set to true on any tested model. Dhw has priority over ch. As result I'm using following algorithm:
- if any flame and no ch flame - it is dhw flame
- if any flame and dhw temperatures are reported and they rise with time - it is dhw flame (not always supported)
- if any flame and dhw is reported for some reason - it is dhw flame
- if dhw temperature not supported and any flame - it is dhw flame. This is why you see both as otherwise it is basically unknown value for binary sensor.

I have not seen request that indicates dhw flame directly and I have no idea how to overcome this issue.
So unless there are ideas nothing I can do.

**Comment by chomupashchuk** [comment]
just for information: i have tested case, when CH should have heated room and turned on tap water to force DHW use.
Due to single valve DHW is in fact heating, but CH flame is reported by Ariston server as if it is being attempted.
That is why it is not that simple to identify DHW flame with CH flame being reported as true and thus I can only choose between true/false/undefined

**Comment by ovimano** [comment]
Since the DHW flame is generaly not suported, can you make a custom binary sensor where you apply the "if any flame and no ch flame - it is dhw flame" rule only?

**Comment by chomupashchuk** [comment]
I have mentioned in README that value is approximated due to lack of data.

Note that we have cases: 
1) any flame and no CH (meaning DHW is ON) 
2) no flames (meaning DHW is OFF) 
3) any flame and CH (DHW is unknown as Ariston server reports CH flame regardless if it is DHW or CH at the moment).

Algorithm mentioned by you works in 1st and 2nd cases but not the 3rd and issue you are describing is a 3rd case.
3rd case is where it is impossible to determine correctly if CH or DHW should be set based on received data.
If boiler has water tank and current temperature of DHW is reported there is algorithm I have written to track changes in temperature to assume DHW (rising) or CH (same or lowering). If it is not reported I must hardcode it to some value and I chose true/ON. I might as well make it unavailable for the matter.

So is your suggestion to assume DHW as always OFF when CH is being reported even if it is not true (as it can be either CH or DHW)?

At some point there was a configuration parameter to select hardcoded value in that specific situation but I did not like additional complexity for the core api (which is also used not only in Home Assistant).

P.S.: It is not a first time I have a discussion regarding this sensor and so far I have not received an idea that I like regarding 3rd case.
