### ISSUE TITLE
Cooling consumption missing

### ISSUE THREAD

**Issue by MatteoGhittorelli** [chomupashchuk/ariston-remotethermo-home-assistant-v2#2]
Dear, 

would it be possibile to add the cooling consumption as sensors for the supported heat pumps?

Best regards
Matteo

**Comment by chomupashchuk** [comment]
Hi,

Since it is reverse engineering and my boiler does not support heat pump, I am not sure how the data might look like in the requests (and if it is present in currently handled ones). You may set "store_files: true" within configuration.yaml and check if mentioned consumption is present in one of the files and which data it is (note that energy/water cunsumption is split into periods as x1 and y1 or smth., which are summer up by applications). If data is not present, analyzer would have to be used for your boiler.

**Comment by MatteoGhittorelli** [comment]
Hi,

	I can give you the credentials in private if you want.

Thanks

**Comment by chomupashchuk** [comment]
Hi,

Due to my work I have a lot less free time lately for such projects. It is an option to share credentials (for example use some temporary password), but not sure when I'll actually have time (could be a week or even more, maybe less).

BR,
Oleh

**Comment by MatteoGhittorelli** [comment]
Dear, 
  no problem at all. I can wait. Please find attached  the gas json file. 
[data_ariston_get_gas _json.txt](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/files/5179812/data_ariston_get_gas._json.txt)



Best regards

**Comment by chomupashchuk** [comment]
I can see that COOLING is marked as "y3" data, so no need for credentials, this is enough data already.

**Comment by chomupashchuk** [comment]
You may try the latest version (probably restart HA after uploading new files before adding new sensors to configuration.yaml to ensure that new files are compiled). Names of sensors are included in REAMDE section.

**Comment by MatteoGhittorelli** [comment]
Works Perfectly! Thanks!
