### ISSUE TITLE
Genus Ones System 35 Pressure reading

### ISSUE THREAD

**Issue by facuzestoa** [chomupashchuk/ariston-remotethermo-home-assistant-v2#23]
Hi Im using your integration since a while in homeassistant and allways working well.
I was wondering if it is possible to have the water pressure reading that is it in the from panel of the boiler and also in the mobile app. (I couldnt find the pressure reading on https://www.ariston-net.remotethermo.com/ page)

Is not really an issue but a feature request, but i dont know how to ask you about that, sorry is not the proper place.

Here screen shot from mobile app with pressure reading  I mention
![image](https://user-images.githubusercontent.com/68237825/136707199-d108d65b-65b5-4805-a97a-8473fcaaf913.png)

Best, Facundo

**Comment by chomupashchuk** [comment]
I have looked into it some time ago and not sure how to handle it properly. All other requests use GET method (simply read data), but with water pressure it uses POST method (meaning set data). I'm not sure from where some data is taken for that request that makes me worry about compatibility for other users even if I make it work for one user. It also requires sniffing phone requests rather than browser requests, which is doable, but might bring some complexity to fill in missing data.

My boiler does not support pressure and I'm kinda worried about setting some unsupported things on someone elses boiler during tests in order to include this sensor and there is a risk that it might affect other users in a negative way. 
For example I included in README information not to include some sensors for some specific boilers, but people still do and then raise tickets. It is hard to make automated identification of supported features without documentation as everything is reverse engineering.

So unless someone agrees to lend hardware access for tests (with risks of improper configuration) and it would be tested on unsupported hardware to make sure it does not cause issues (except events in integration rather than boiler itself), I would rather not even start.

**Comment by facuzestoa** [comment]
Hi, thanks for your prompt Sunday reply :-)
I understand your point on compatibility with other models and fully agree with you that would probably bring more complications than benefits, my request came as during last winter season I experienced some pressure drops due to small leaks on some heaters that lead with reaching less than 0.5 Barg where the boiler is not starting anymore until you top up pressure. But I followed using the app so we can say that the request was like a "nice to have".

Regarding lending hardware to test, I'm sorry but I cannot do that, I had some issues in the past when I switched my boiler to dual mode (hot water + heater): I do not have hot water system installed only heating system. The boiler started doing thermal disinfection and poped up the safety valve due to overpressure releasing a lot of high temp vapour inside the boiler room. It is something a bit dangerous.

Thanks again, I really appreciate the job you do with this Ariston integration.

Best, Facundo
