### ISSUE TITLE
Ariston Genius One  - 3 zone 

### ISSUE THREAD

**Issue by itmcompl** [chomupashchuk/ariston-remotethermo-home-assistant-v2#24]
Hi,
I have an Ariston Genius One gas stove, 3 additional zones Bathroom, bedroom and garage. Integrating this with HA, I only have the first visible zone, i.e. Zone 1 - Garage. By logging into the account on the aristona website, I can see all zones. Is it possible to read all zones into the HA? possibly tempretatura control on each separately?

**Comment by chomupashchuk** [comment]
The problem is that my boiler has just 1 zone and the boilers I got temporary access to also had just 1 zone and thus whole integration was designed with just 1 zone in mind. I have no idea how data would look like in the requests (it is a reverse engineering project). It is not just fetching data as sensors, which would require access to equipment with multiple nodes, also some mechanism to distinguish it via different entities (climate) as part of HA integration would have to be thought of. I do not want to spend too much personal time on improvements, so potentially I could have a look (if access is provided) to estimate amount of work, but can't guarantee anything at this point. It should be possible to achieve from technical point of view, the only question is time and complexity and if I would be willing to invest estimated amount of personal time.

**Comment by itmcompl** [comment]
I understand, then what would you need for access?

**Comment by chomupashchuk** [comment]
Email and password (can be set to new value during review/tests) to access data on Ariston site, and can be sent via email (chomu.nattsol@gmail.com) to not be included here.

**Comment by itmcompl** [comment]
ok, I send.

**Comment by vmanuel** [comment]
Just saw last commits! I wiill try!

**Comment by vmanuel** [comment]
![image](https://user-images.githubusercontent.com/5447125/143723292-24296abe-c842-4494-ac0e-c2f552efe23d.png)
Working for me!
