### ISSUE TITLE
ariston genus one - CH Flow Temperature

### ISSUE THREAD

**Issue by rad0cea** [chomupashchuk/ariston-remotethermo-home-assistant-v2#27]
Hello,
I am using HA 6.6
core-2021.11.5
supervisor-2021.12.1
/config/custom_components/ariston/ariston.py _VERSION = "1.0.47"

i am trying to enable ch_water_temperature, trying to obtain the "CH Flow temperature":

ariston:
  username: !secret ariston_user
  password: !secret ariston_password
  sensors:
    - ch_water_temperature
    - outside_temperature
    - ch_detected_temperature
    - ch_mode
    - ch_set_temperature
    - dhw_set_temperature
    - dhw_storage_temperature
    - errors_count
    - mode
  binary_sensors:
    - changing_data
    - online
  selector:
    - mode
    - ch_mode

CH water temperature shows as unavailable in lovelace
![image](https://user-images.githubusercontent.com/95982661/145690586-6fd9fb21-518d-48bc-8452-c21ab4ac25da.png)

and the log says:
Logger: custom_components.ariston.ariston
Source: custom_components/ariston/ariston.py:2240
Integration: Ariston (documentation, issues)
First occurred: 22:17:44 (1 occurrences)
Last logged: 22:17:44
 <custom_components.ariston.ariston.AristonHandler object at 0xb0e1ac10> Unsupported sensors detected: {'ch_water_temperature'}, disable corresponding binary_sensors/sensors/switches in the configuration 

==== 
even so the iPhone app shows the CH flow temperature on this appliance (see screenshot)
![image](https://user-images.githubusercontent.com/95982661/145690531-6a628797-765c-4142-abc5-1bb1312909f4.png)

is it any way to have this fixed or have the water temp retrieved in HA ?
Thanks

**Comment by chomupashchuk** [comment]
My boiler does not support that sensor. It was added based on data fetched from people, who provided credentials to reverse engineer additional data. I can't say anything for sure if there is special handling for some boilers or something was broken during some update.
Also I'm not sure if it is the same sensor or not (it was parameter 6.3.0.0 in user menu when sensor was added). From what I remember, at least pressure had very odd handling (once again my boiler has no such data, so I can't check it), that data on this page has POST request and was available only on this page in the application, which required special data as input, but I can be wrong as it was more than a half a year ago. The integration reproduces web browser requests towards https://www.ariston-net.remotethermo.com . Do you see that sensor in web browser on one of the pages?

In order to get data for me to have a look, there are few options:
1. You may analyze requests via fiddler, login via web browser and gather requests data for the sensor you are interetsed in
2. You may connect phone via proxy within fiddler and open required page on the phone and gather data in the fiddler
3. Provide credentails for me to perform the steps

**Comment by chomupashchuk** [comment]
I see that implemented version of `ch_water_temperature` is supported to be set. If in your case `CH Flow Setpoint Temp` is read-only, then most likely those are completely different parameters and there is no support for parameter  `CH Flow Setpoint Temp`.
If that is the case, the value is probably accessible only Android/IOS application. I no longer have the data I've gathered via sniffing requests from Android application for that specific page to confirm or deny this.
If the POST method is used, I would rather avoid it as POST usually means setting of data in the boiler (all other requests are GET methods, meaning just reading data), which creates some risks that integration shall change something unexpectedly. At least as I remeber, there was data in POST request, which I could not find values from other requests and hardcoding them brings risk for other users, as there are many boilers with special configurations.

**Comment by rad0cea** [comment]
Hello,
Considering the above, is there any chance to have this implemented for Ariston Genus One boylers ?
I am willing to help with data you require.

**Comment by rad0cea** [comment]
regarding info shown on https://www.ariston-net.remotethermo.com

I do not se the CH Flow Setpoint, I only can adjut the AUTO function deviation![image](https://user-images.githubusercontent.com/95982661/145706512-0b70fc9e-78c7-4092-868e-939599e44bbc.png)

However on iOS App I see this info in "appliance" section.

![image](https://user-images.githubusercontent.com/95982661/145706554-bb80c5ef-8aa0-4804-ab6f-055bec97769a.jpeg)
![image](https://user-images.githubusercontent.com/95982661/145706563-1dde0e92-1aca-4197-80ce-c42a0c4dbbba.jpeg)

**Comment by chomupashchuk** [comment]
There are 2 options:
1. you collect the data on specific requests. I use `fiddler` application for this purpose, where I start proxy server on `fiddler`, enable https decoding and in my Android phone enable proxy for wifi connection and specify `fiddler` proxy. The I open requests, which include ariston website (top is what sent and bottom is what received) and copy the whole data from those pages in `raw` view. When connected, open on the phone specific page (refresh would sent request, which should be fetched by fiddelr) to gather data on specific sensors.
2. you provide me with credentials (password can be temporary changed for example) for me to collect the data by mentioned method above.

Some people prefer first method, some second. Note that if it is GET method - it is relatively safe and simple. If it would be POST method, then it creates risk of not having full set of data to be sent (as mentioned before there are many users of integration with different hardware) and POST usually means changing configuration in the boiler, so it is preferred that necessary data is known, which is somewhat risky for unknown data values depending on the hardware. So if POST method used, then there will be few options: 1) you allow me to change parameters in POST request to test how safe it is to hardcode some values 2) do nothing 3) hardcode value and indicate in readme potential risks, but since peolple do not read what I write, it it likely that I can get many-many tickets, that I do not want to handle.

That is basically the situation and possible outcomes

**Comment by rad0cea** [comment]
Please send a private message with your email. Thanks

**Comment by chomupashchuk** [comment]
My email is chomu.nattsol@gmail.com

**Comment by chomupashchuk** [comment]
I just got acces to other boiler. You may try replacing with attached files and restarting HA.
New sensors `ch_flow_temperature` and `pressure` can be specified.
Please give feedback ASAP so that I could publish new release.
[sensor.zip](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/files/7705904/sensor.zip)

**Comment by rad0cea** [comment]
Hello
First is that files have a different charset and HA does not see the correct line terminator:

wrong:
![image](https://user-images.githubusercontent.com/95982661/145879582-90d42036-322c-4a8d-87a1-185a58b6dbac.png)

and after correction:
![image](https://user-images.githubusercontent.com/95982661/145879700-61c153bd-4b96-49b3-826f-488cae741e7d.png)

but HA check configuration still show error
![image](https://user-images.githubusercontent.com/95982661/145880114-f7717242-73bc-4db4-9a1c-49a52d9c74d5.png)

**Comment by chomupashchuk** [comment]
New sensors can be added in configuration.yaml after HA restart.
I don't know why there should be a problem with character set considering that same files were copied to HA core's mounted storage and data could be fetched successfully. I've sent zip to other guy and it works for him as well, I belive he uses HASSIO.

**Comment by chomupashchuk** [comment]
I do use windows but this is the first time I've heard that EOL characters caused issues somewhere, considering that more than 100 people use integrations and in different versions. I did encounter issues with git and some random character being set instead of ascii when mix of OS is used, but here I can't understand why you have issues.

**Comment by rad0cea** [comment]
Hello,
As per latest file shared, the data is now present in HA
![image](https://user-images.githubusercontent.com/95982661/145933128-d1167259-4bef-4587-99d9-09570f2c205b.png)
I can also see CH circuit water pressure
![image](https://user-images.githubusercontent.com/95982661/145934350-752b860c-03e6-4db1-9e2c-da682c392de1.png)

Many Thanks !

Question, how can I change the CH Fixed Temperature as a DIAL as you can change the CH Set Temperature ?
See below DIAL proposal
![image](https://user-images.githubusercontent.com/95982661/145933745-1bc9ab59-152b-4345-9ab6-2ba5c6a54726.png)

Best wishes !

**Comment by chomupashchuk** [comment]
Dials are frontend, which is outside of component handling. There are options to use services and sensors from some entity controlled by frontend. I'm working on generation of `select` entities to set some additional temperatures, but probably a custom dial would have to be created for such entity types. I have created a ticket almost a year ago to have dial for water_heater entity in HA itself - still nothing.

**Comment by rad0cea** [comment]
Everything looks great. This issue can be closed
![image](https://user-images.githubusercontent.com/95982661/146053761-49412033-0d3e-439a-96dd-113c1c3b9105.png)

Thank you so much for your help !
