### ISSUE TITLE
Ariston unavailable

### ISSUE THREAD

**Issue by Ric199021** [chomupashchuk/ariston-remotethermo-home-assistant-v2#37]
Hi, again Ariston is unavailable. I'm using the latest software, everything went fine until this morning. 
7_11_2022
Remotely https://www.ariston-net.remotethermo.com/ is working and from app also is working.

**Comment by simille83** [comment]
> Hi, again Ariston is unavailable. I'm using the latest software, everything went fine until this morning. 7_11_2022 Remotely https://www.ariston-net.remotethermo.com/ is working and from app also is working.

Hi, I also have the same problem since this morning.

**Comment by floringhimie** [comment]
Me too

**Comment by Frowxen** [comment]
Hi, I'm having the same issue since this morning, Ariston web is running properly and shows that there's conection.

**Comment by bazantos** [comment]
The same issue

**Comment by Zolli** [comment]
I experience the same issue that others mentioned. 

I try to investigate the issue and looks like the login page is switched to a new version and the URL where the login data is need to be posted is changed, so the server gives back 404 to the http client. I think just the login process needs some minor adjustment.

Edit: Sure enough, the new POST URL is prefixed with an R2 string, so the new url is: `https://www.ariston-net.remotethermo.com/R2/Account/Login` and looks like every url contains that R2 string now

**Comment by Ric199021** [comment]
> I experience the same issue that others mentioned. 
> 
> 
> 
> I try to investigate the issue and looks like the login page is switched to a new version and the URL where the login data is need to be posted is changed, so the server gives back 404 to the http client. I think just the login process needs some minor adjustment.
> 
> 
> 
> Edit: Sure enough, the new POST URL is prefixed with an R2 string, so the new url is: `https://www.ariston-net.remotethermo.com/R2/Account/Login` and looks like every url contains that R2 string now

Cool debug, 404 is always a bad sign. Yes they change the login page now you have to select the region also or the language, maybe there is something.

**Comment by chomupashchuk** [comment]
Arison switched to new requests (different set of data) and new URLs for everything, 
You may check  if version prepared by other developer would work: https://github.com/fustom/ariston-remotethermo-home-assistant-v3
I don't know when i'll have time to work on this vesrion soon.

**Comment by Jedrek2021** [comment]
I checked https://github.com/fustom/ariston-remotethermo-home-assistant-v3 its work ok. Unfortunately there are not a few sensors, your version was very good for Genus One

**Comment by Engine1992** [comment]
The same problem... Waiting for update ;) Your integration is the best @chomupashchuk

**Comment by michtate** [comment]
Hi,

for me ...-v3 is nice but usless :( - only gas boilers and lack of used energy for heat pump

**Comment by dtalens** [comment]
It works for me again, thanks.

**Comment by Ric199021** [comment]
> It works for me again, thanks.

For me is not working, just restarted home assistant without any success.

**Comment by Engine1992** [comment]
> It works for me again, thanks.

No way... For me not working 🤦

**Comment by pico1881** [comment]
@chomupashchuk  I hope you have time to update your very good integration because the V3 for me does not work with Ariston Nimbus

**Comment by dcarotenuto** [comment]
Sorry, not working for me, all sensors are unavailable

**Comment by chomupashchuk** [comment]
So Ariston no longer supports requests based on which integration was written. Completely different requests and data structures within forced me to almost rewrite API part and interaction with it ( https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/commit/70d78c5ea6cde832d1825c8c78dcb694cbd0cb89 ).

It was updated to work for my own boiler, which has limited functionality compared to other bolers and as a result number of old sensors will not work, also some changes in configuration.yaml structure (view README.md for latest configuration).
Extended functionality would require:
- option 1: get access to boilers with more functionality for me to use Fiddler to analyze requests, so that I could replicate them (I'm not a magician to code something that I have no idea how it looks like)
- option 2: for you to use Fiddler or other tool for traffic analyzing and provide additional information (for example old energy use had internal markings and by comparing values with web representation it was possible to map marking to water/gas/electricity)
- option 3: you make fetch the data, make a branch on github, make updates to the code and make a pull request.

It already took ~30 hours of my time this week (you may browse files changes: https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/commit/70d78c5ea6cde832d1825c8c78dcb694cbd0cb89 ) for which I do not get payed (I have a full time job besides this).
Consider donating to support Ukrainian army (some options described in https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/blob/master/DONATE_README.MD ) or other humanitarian organizations. It is a stressful atmosphere in my country and thus I do not have any motivation to spend a lot of my personal time on side projects unless it would at least motivate others to help out (it can be other ways such as supporting ukrainian refugees in your contry, donating drugs/food etc. not just supporting military).

**Comment by mirceamaris** [comment]
Thank you for all your work. Be safe!

**Comment by VoyteckPL** [comment]
These 2 selectors don't work:

#    - dhw_comfort_temperature
#    - dhw_economy_temperature

**Comment by dtalens** [comment]
> Per tant, Ariston ja no admet sol·licituds basades en la qual s'ha escrit la integració. Les sol·licituds i les estructures de dades completament diferents em van obligar a gairebé reescriure la part de l'API i la interacció amb ella ( [70d78c5](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/commit/70d78c5ea6cde832d1825c8c78dcb694cbd0cb89) ).
> 
> S'ha actualitzat per funcionar per a la meva pròpia caldera, que té una funcionalitat limitada en comparació amb altres bolers i, com a conseqüència, no funcionarà un nombre de sensors antics, també alguns canvis en l'estructura configuration.yaml (vegeu README.md per a la darrera configuració). La funcionalitat ampliada requeriria:
> 
> * opció 1: obtenir accés a calderes amb més funcionalitats perquè utilitzi Fiddler per analitzar les sol·licituds, de manera que les pugui replicar (no sóc mag per codificar alguna cosa que no tinc ni idea de com es veu)
> * opció 2: perquè utilitzeu Fiddler o una altra eina per analitzar el trànsit i proporcionar informació addicional (per exemple, l'antic consum d'energia tenia marques internes i comparant els valors amb la representació web era possible mapejar el marcatge amb aigua/gas/electricitat)
> * opció 3: feu obtenir les dades, feu una branca a github, feu actualitzacions del codi i feu una sol·licitud d'extracció.
> 
> Aquesta setmana ja m'han trigat ~ 30 hores del meu temps (pot consultar els canvis de fitxers: [70d78c5](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/commit/70d78c5ea6cde832d1825c8c78dcb694cbd0cb89) ) per les quals no em paguen (tinc una feina a temps complet a més d'això). Penseu en fer una donació per donar suport a l'exèrcit ucraïnès (algunes opcions descrites a https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/blob/master/DONATE_README.MD ) o altres organitzacions humanitàries. És un ambient estressant al meu país i, per tant, no tinc cap motivació per dedicar gran part del meu temps personal a projectes paralels, tret que almenys motivi els altres a ajudar (pot ser d'altres maneres, com ara donar suport als refugiats ucraïnesos al vostre país). país, donar drogues/aliments, etc. no només donar suport a l'exèrcit).

Thank you for your time and effort.

**Comment by Jedrek2021** [comment]
All clear, Thank you for all your work. Be safe!

**Comment by pico1881** [comment]
DHW_STORAGE_TEMPERATURE and WATER HEATER unavailable , how can I add this sensor?
Using Fiddler i found the menu code "U6_26_5" and this is the response in main page {"id":"DhwStorageTemperature","zone":0,"kind":1,"min":-3277.0,"max":3276.0,"step":1.0,"value":41.0,"decimals":0,"options":null,"optTexts":null,"readOnly":true,"error":false,"invalid":false,"expiresOn":null,"unit":"°C"},

**Comment by chomupashchuk** [comment]
@pico1881 , @VoyteckPL  please create a separate tickets for new issues.

Regarding DHW comfort/economy temperatures they were not added partly intentional. In the latest version some requests are based on Android application rather than Ariston website. The reasons are less frequent changes in requests between Android/IOS API and seems to have better processing speed (in 2 days seems like different amount of errors and timeouts if to compare Android/IOS API and Web interface). The intention was to see if other boilers with DHW scheduling supported would have requests in Android application to handle it together with CH temperatures. I have rewrittem much from the scratch and removed not used data (otherwise maintenance would be terrible) and did not want to implement temporary and redo something afterwards. Using web interface requests was a plan B for this specific functionality if not supported in Android/IOS API.
My boiler does not have DHW comfort and economy, only 1 temperature.
You may start Fiddler proxy server and configure on Android proxy server from Fiddler ( https://www.telerik.com/blogs/how-to-capture-android-traffic-with-fiddler ), switch between pages and check:
- if one of pages fetches DHW schedule (if supported). I expect that if there is comort and economy then schedule should be present. It is not present in my case.
- If Android/IOS has option to read and set DHW comfort and economy temperatures.
- if energy use is supported then provide with requests data and possibly screenshots to map data with displayed values. In my case I see lists with dictionaries with few 1-letter keys and zeros.

My water_heater is available and it might be the difference in data within the requests (for example instead of 1 parameter for DHW temperature there are in fact 2 completely different parameters that would result in issue that parameter used to identify working water_heater would differ from case to case - but it is just an assumption).

Previosly DHW storage temperature was fetched from web interface and I do not know where that data is now. Preferrably it is available in Android/IOS API, if not, then has to be checked using Fiddler on web interface.
