### ISSUE TITLE
From date 11/07/2022  I have a connection problem with ariston remotethermo

### ISSUE THREAD

**Issue by andrearomanoif** [chomupashchuk/ariston-remotethermo-home-assistant-v2#38]
Log show this messages and integration is down: 

Logger: custom_components.ariston.ariston
Source: custom_components/ariston/ariston.py:3089
Integration: Ariston (documentation, issues)
First occurred: 22:28:57 (15 occurrences)
Last logged: 22:42:57

ariston action nok for _get_main: Login unexpected reply code

Logger: custom_components.ariston.ariston
Source: custom_components/ariston/ariston.py:3066
Integration: Ariston (documentation, issues)
First occurred: 22:28:57 (15 occurrences)
Last logged: 22:42:57

Connection errors: 11
Connection errors: 12
Connection errors: 13
Connection errors: 14
Connection errors: 15

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.ariston.ariston
Source: custom_components/ariston/ariston.py:1571
Integration: Ariston (documentation, issues)
First occurred: 22:28:57 (15 occurrences)
Last logged: 22:42:57

<custom_components.ariston.ariston.AristonHandler object at 0xabaffcd0> Unexpected reply during login: 404

**Comment by dcarotenuto** [comment]
I has the same problem too: debugging a little, I found that the url to call for login changed from _ARISTON_URL/Account/Login to _ARISTON_URL/**R2**/Account/Login, but this is not enough to solve the issue, because the response url is different from expected: remains the same (/R2/Account/Login) and than there is a redirect to dashboard  https://www.ariston-net.remotethermo.com/R2/Plant/Index/XXXXXXXXXX?navMenuItem=0&breadcrumbPath=0.

I hope this helps the developer to fix the issue.

Thanks a lot for your job

**Comment by StanimirS** [comment]
Same issue here, although I am using the old version, because I have a velis boiler

**Comment by simille83** [comment]
https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/issues/37

**Comment by chomupashchuk** [comment]
Duplicate
